# Unit/Integration Test for Seurat Object Audit
# Verifies the structure and content of the generated audit outputs.

library(jsonlite)
source("scripts/R/logging_utils.R")

setup_strict_logging()
log_info("Starting audit output validation tests...", stage = "test_audit")

# Output files to validate (these should be generated by running the audit script on synthetic data)
audit_md <- "reports/DATA_AUDIT.md"
structure_tsv <- "reports/DATASET_STRUCTURE.tsv"
inventory_json <- "reports/object_inventory.json"
inventory_tsv <- "reports/object_inventory.tsv"
m1_report <- "reports/milestones/M1_REPORT.md"
prov_json <- "reports/audits/m1_audit_provenance.json"

test_file_exists <- function(filepath) {
  if (!file.exists(filepath)) {
    log_error(sprintf("Required file does not exist: %s", filepath), stage = "test_audit")
    return(FALSE)
  }
  if (file.info(filepath)$size == 0) {
    log_error(sprintf("Required file is empty: %s", filepath), stage = "test_audit")
    return(FALSE)
  }
  log_info(sprintf("File %s exists and is non-empty.", filepath), stage = "test_audit")
  return(TRUE)
}

# Run existence checks
files_exist <- all(sapply(c(audit_md, structure_tsv, inventory_json, inventory_tsv, m1_report, prov_json), test_file_exists))
if (!files_exist) {
  log_error("File presence verification failed.", stage = "test_audit")
  quit(status = 1)
}

# Validate JSON content
log_info("Validating object_inventory.json structure...", stage = "test_audit")
inv <- tryCatch({
  read_json(inventory_json, simplifyVector = TRUE)
}, error = function(e) {
  log_error(sprintf("Failed to parse JSON: %s", conditionMessage(e)), stage = "test_audit")
  return(NULL)
})

if (is.null(inv)) quit(status = 1)

required_fields <- c(
  "object_class", "seurat_version", "file_size", "dimensions", 
  "assays", "default_assay", "raw_rna_counts_exist", "reductions", 
  "graphs", "metadata_schema", "candidate_dataset_variables", 
  "reprocessing_possible", "dataset_recommendation"
)

for (f in required_fields) {
  if (!f %in% names(inv)) {
    log_error(sprintf("Missing required key in JSON inventory: %s", f), stage = "test_audit")
    quit(status = 1)
  }
}
log_info("JSON inventory structure is valid.", stage = "test_audit")

# Validate structure TSV content
log_info("Validating DATASET_STRUCTURE.tsv content...", stage = "test_audit")
struct <- tryCatch({
  read.table(structure_tsv, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
}, error = function(e) {
  log_error(sprintf("Failed to read TSV: %s", conditionMessage(e)), stage = "test_audit")
  return(NULL)
})

if (is.null(struct)) quit(status = 1)

# Check columns (sample_id, orig.ident, cell_count or similar)
if (!("sample_id" %in% colnames(struct) && "orig.ident" %in% colnames(struct) && "cell_count" %in% colnames(struct))) {
  # If synthetic data doesn't have both, it might fall back, but let's check
  log_warn("DATASET_STRUCTURE.tsv does not have standard columns: sample_id, orig.ident, cell_count", stage = "test_audit")
} else {
  log_info("DATASET_STRUCTURE.tsv column structure is valid.", stage = "test_audit")
}

# Validate provenance JSON content
log_info("Validating provenance JSON...", stage = "test_audit")
prov <- tryCatch({
  read_json(prov_json, simplifyVector = TRUE)
}, error = function(e) {
  log_error(sprintf("Failed to parse provenance JSON: %s", conditionMessage(e)), stage = "test_audit")
  return(NULL)
})

if (is.null(prov)) quit(status = 1)

required_prov_fields <- c("timestamp", "step", "git_commit", "inputs", "outputs", "parameters")
for (pf in required_prov_fields) {
  if (!pf %in% names(prov)) {
    log_error(sprintf("Missing required key in provenance JSON: %s", pf), stage = "test_audit")
    quit(status = 1)
  }
}
log_info("Provenance structure is valid.", stage = "test_audit")

log_info("All audit output validation tests PASSED.", stage = "test_audit")
quit(status = 0)
